# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: äº¬å–œå·¥å‚å›¢ID_json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23,0-16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateFactoryTuanID
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: 'è¿è¡Œ ã€æ›´æ–°äº¬å–œå·¥å‚å¼€å›¢IDã€‘'
        run: |
          node jd_jxFactoryCreateTuan.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update by Github Action" -a || echo "Nothing to update"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main

      # å•ä¸€ä»“åº“å†…å®¹å†…å®¹åŒæ­¥åˆ°è‡ªå·±çš„giteeä¸Š
      - name: å¼€å§‹åŒæ­¥ã€MyUpdateTeamã€‘ä»“åº“ğŸ”„
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/h455257166
          dst: gitee/h455257166
          static_list: "MyUpdateTeam"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          debug: true
